//Q2 Yes, code execution continues after the catch block if an error is caught.
// If there's a finally block, it is executed,
// and then the program continues executing the code after
//  the entire try...catch...finally statement.
